services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh: docker exec -u erp -it erp bash
    #
    erp:
      #'Repository Path' taken from https://abasartifactory.jfrog.io/ui/repos/tree/General/customer/abas/neumand
      image: "abasartifactory.jfrog.io/customer/abas/neumand:${targetErpVersion}"
      init: true
      container_name: "${targetErpVersion:-erp}"

      ports:
      - "${SSH_TEST_PORT:-2205}:22"
      - "${MINI_GUI_PORT:-8001}:80"
      - "${EDP_TEST_PORT:-6560}:6550"
      - "${GUI_TEST_PORT:-48592}:48392"

      environment:
#      - ABAS_HOST=${ABAS_HOST}
      - ABAS_GUI_PORT=${GUI_TEST_PORT:-48592}

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau
#      command: ["sh", "-c", "cd /abas/erp && eval $$(sh denv.sh) && datmeta -s && /abas/bin/starteVersion.sh run" ]
      command: /abas/bin/starteVersion.sh run

      mem_limit: 4g
      healthcheck:
        test: netstat -ltn | grep -c 18056
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 5s

    # nexus for publishing abas Essentials libraries
#    nexus:
#      image: sonatype/nexus:oss
#      container_name: "nexus"
#      ports:
#      - "8081:8081"
